#exceptions
#order
exception.order.vendorpartnumber.notexist=\u8ba2\u5355{0}\u7684\u5b50\u8ba2\u5355{1}\u5173\u8054\u7684\u5546\u54c1\u5916\u90e8\u5546\u5bb6\u7f16\u7801\u672a\u586b\u5199

#task
exception.task.duplicate={0}\u6e20\u9053{1}\u5e94\u7528\u7684{2}-{3}\u7c7b\u578btask\u4e1a\u52a1\u91cd\u590d

#api
exception.api.invoke={0}\u6e20\u9053{1}\u5e94\u7528\u7684api{2}\u8c03\u7528\u5931\u8d25
exception.api.invoke.response.null={0}\u6e20\u9053{1}\u5e94\u7528\u7684api{2}\u8c03\u7528response\u4e3a\u7a7a
exception.api.connect.error=\u5e94\u7528{0}\u8fde\u63a5\u5230{1}\u51fa\u9519

exception.connector.initial.err={0}\u6e20\u9053\u7684{}\u5e94\u7528\u521d\u59cb\u5316\u5931\u8d25

exception.data.transform={0}\u6a21\u5757\u6570\u636e\u8f6c\u6362\u5931\u8d25:{1}